// =============================================================================
// Seed — attribute produk lengkap per kategori toko bangunan (Indonesia).
// Standar penamaan, spesifikasi untuk kasir & pelanggan, template import terstruktur.
// =============================================================================

import { CANONICAL_ATTRIBUTE_CATEGORIES } from "@/lib/category-attribute-map";
import type { ProductAttributeDefinition } from "@/types/product-attributes";

export const ATTRIBUTE_SEED_VERSION = 2;

export const SEED_PRODUCT_ATTRIBUTE_CATEGORIES = CANONICAL_ATTRIBUTE_CATEGORIES;

function val(
  id: string,
  label: string,
  abbreviation: string,
  sortOrder: number,
): ProductAttributeDefinition["values"][0] {
  return { id, label, abbreviation, sortOrder, isActive: true };
}

function attr(
  id: string,
  categoryName: string,
  name: string,
  sortOrder: number,
  values: ProductAttributeDefinition["values"],
): ProductAttributeDefinition {
  return { id, categoryName, name, sortOrder, isActive: true, values };
}

export function getSeedProductAttributes(): ProductAttributeDefinition[] {
  return [
    attr("attr-sbt-jenis", "Semen & Beton", "Jenis", 1, [
      val("sbt-j-1", "Semen Portland", "SEM", 1),
      val("sbt-j-2", "Semen PPC / Composite", "PPC", 2),
      val("sbt-j-3", "Mortar Instan", "MRT", 3),
      val("sbt-j-4", "Semen Putih", "SPW", 4),
      val("sbt-j-5", "Admixture / Additive", "ADM", 5),
      val("sbt-j-6", "Semen Quick Setting", "QCK", 6),
    ]),
    attr("attr-sbt-kemasan", "Semen & Beton", "Kemasan", 2, [
      val("sbt-k-1", "50 kg", "50KG", 1),
      val("sbt-k-2", "40 kg", "40KG", 2),
      val("sbt-k-3", "25 kg", "25KG", 3),
      val("sbt-k-4", "20 kg", "20KG", 4),
      val("sbt-k-5", "5 kg", "5KG", 5),
    ]),
    attr("attr-sbt-tipe", "Semen & Beton", "Tipe", 3, [
      val("sbt-t-1", "Standard", "STD", 1),
      val("sbt-t-2", "Premium", "PRM", 2),
      val("sbt-t-3", "Super / Composite", "SUP", 3),
      val("sbt-t-4", "Masonry / Pasangan", "MSN", 4),
      val("sbt-t-5", "Waterproof", "WPF", 5),
    ]),
    attr("attr-sbt-aplikasi", "Semen & Beton", "Aplikasi", 4, [
      val("sbt-a-1", "Struktur / Cor", "STR", 1),
      val("sbt-a-2", "Plester", "PLS", 2),
      val("sbt-a-3", "Finishing", "FNS", 3),
      val("sbt-a-4", "Grouting", "GRT", 4),
      val("sbt-a-5", "Umum", "UMM", 5),
    ]),
    attr("attr-sbt-merk", "Semen & Beton", "Merk", 5, [
      val("sbt-m-1", "Tiga Roda", "TRD", 1),
      val("sbt-m-2", "Semen Gresik", "GRS", 2),
      val("sbt-m-3", "Holcim", "HLC", 3),
      val("sbt-m-4", "Semen Padang", "SPD", 4),
      val("sbt-m-5", "Dyno / Semen Indonesia", "DYN", 5),
      val("sbt-m-6", "Master", "MST", 6),
    ]),

    attr("attr-btb-jenis", "Bata & Blok", "Jenis", 1, [
      val("btb-j-1", "Bata Merah", "BMR", 1),
      val("btb-j-2", "Bata Press", "BPR", 2),
      val("btb-j-3", "Batako", "BTK", 3),
      val("btb-j-4", "Hebel / AAC", "HBL", 4),
      val("btb-j-5", "Roster / Border", "RST", 5),
      val("btb-j-6", "Bata Expose", "BEX", 6),
    ]),
    attr("attr-btb-ukuran", "Bata & Blok", "Ukuran", 2, [
      val("btb-u-1", "Standard", "STD", 1),
      val("btb-u-2", "7.5 cm", "75", 2),
      val("btb-u-3", "10 cm", "10", 3),
      val("btb-u-4", "15x30x60 cm", "153060", 4),
      val("btb-u-5", "20x40x60 cm", "204060", 5),
    ]),
    attr("attr-btb-kualitas", "Bata & Blok", "Kualitas", 3, [
      val("btb-k-1", "Kelas I", "K1", 1),
      val("btb-k-2", "Kelas II", "K2", 2),
      val("btb-k-3", "Ekspor", "EXP", 3),
      val("btb-k-4", "Standard", "STD", 4),
    ]),
    attr("attr-btb-merk", "Bata & Blok", "Merk", 4, [
      val("btb-m-1", "Hebel AAC", "AAC", 1),
      val("btb-m-2", "Citicon", "CTC", 2),
      val("btb-m-3", "Lokal / Custom", "LOC", 3),
      val("btb-m-4", "Merah Super", "MRS", 4),
    ]),

    attr("attr-cat-jenis", "Cat & Finishing", "Jenis", 1, [
      val("ct-jn-1", "Cat Tembok", "TMB", 1),
      val("ct-jn-2", "Cat Kayu", "KYU", 2),
      val("ct-jn-3", "Cat Besi", "BSI", 3),
      val("ct-jn-4", "Plamur", "PLM", 4),
      val("ct-jn-5", "Waterproofing", "WPF", 5),
      val("ct-jn-6", "Lem Kayu / PVA", "LEM", 6),
      val("ct-jn-7", "Thinner / Vernish", "THN", 7),
      val("ct-jn-8", "Dempul / Filler", "DMP", 8),
    ]),
    attr("attr-cat-kemasan", "Cat & Finishing", "Kemasan", 2, [
      val("ct-km-1", "1 kg", "1KG", 1),
      val("ct-km-2", "5 kg", "5KG", 2),
      val("ct-km-3", "20 kg", "20KG", 3),
      val("ct-km-4", "25 kg", "25KG", 4),
      val("ct-km-5", "0.8 L", "08L", 5),
      val("ct-km-6", "4 L", "4L", 6),
      val("ct-km-7", "20 L", "20L", 7),
    ]),
    attr("attr-cat-finish", "Cat & Finishing", "Finishing", 3, [
      val("ct-fn-1", "Interior", "INT", 1),
      val("ct-fn-2", "Exterior", "EXT", 2),
      val("ct-fn-3", "Matt", "MAT", 3),
      val("ct-fn-4", "Gloss / Kilat", "GLS", 4),
      val("ct-fn-5", "Satin / Setengah Kilat", "SAT", 5),
      val("ct-fn-6", "Undercoat / Primer", "UND", 6),
    ]),
    attr("attr-cat-warna", "Cat & Finishing", "Warna", 4, [
      val("ct-wr-1", "Putih", "WHT", 1),
      val("ct-wr-2", "Hitam", "BLK", 2),
      val("ct-wr-3", "Netral / Custom", "NET", 3),
      val("ct-wr-4", "Merah", "RED", 4),
      val("ct-wr-5", "Kuning / Cream", "YLW", 5),
      val("ct-wr-6", "Biru / Hijau", "BLU", 6),
    ]),
    attr("attr-cat-merk", "Cat & Finishing", "Merk", 5, [
      val("ct-mk-1", "Dulux", "DLX", 1),
      val("ct-mk-2", "Avian", "AVN", 2),
      val("ct-mk-3", "Nippon Paint", "NPP", 3),
      val("ct-mk-4", "Propaint", "PRP", 4),
      val("ct-mk-5", "Mowilex", "MWL", 5),
      val("ct-mk-6", "Sika / No Drop", "SIK", 6),
    ]),

    attr("attr-pip-jenis", "Pipa & Sanitasi", "Jenis", 1, [
      val("pv-jn-1", "Pipa PVC", "PIP", 1),
      val("pv-jn-2", "Pipa HDPE", "HDPE", 2),
      val("pv-jn-3", "Pipa PPR", "PPR", 3),
      val("pv-jn-4", "Fitting / Sambungan", "FIT", 4),
      val("pv-jn-5", "Kran / Keran", "KRN", 5),
      val("pv-jn-6", "Closet / WC", "CLS", 6),
      val("pv-jn-7", "Wastafel / Kloset Duduk", "WST", 7),
      val("pv-jn-8", "Floor Drain / Shower", "SHW", 8),
    ]),
    attr("attr-pip-bahan", "Pipa & Sanitasi", "Bahan", 2, [
      val("pv-bh-1", "PVC", "PVC", 1),
      val("pv-bh-2", "HDPE", "HDPE", 2),
      val("pv-bh-3", "PPR", "PPR", 3),
      val("pv-bh-4", "Stainless", "SS", 4),
      val("pv-bh-5", "Kuningan", "KNS", 5),
      val("pv-bh-6", "Akrilik / Keramik", "AKR", 6),
    ]),
    attr("attr-pip-ukuran", "Pipa & Sanitasi", "Ukuran", 3, [
      val("pv-uk-1", '1/2"', "12", 1),
      val("pv-uk-2", '3/4"', "34", 2),
      val("pv-uk-3", '1"', "1", 3),
      val("pv-uk-4", '2"', "2", 4),
      val("pv-uk-5", '3"', "3", 5),
      val("pv-uk-6", '4"', "4", 6),
      val("pv-uk-7", "110 mm", "110", 7),
      val("pv-uk-8", "150 mm", "150", 8),
    ]),
    attr("attr-pip-kelas", "Pipa & Sanitasi", "Kelas", 4, [
      val("pv-kl-1", "AW (Air Bersih)", "AW", 1),
      val("pv-kl-2", "D (Air Kotor)", "D", 2),
      val("pv-kl-3", "R (Tekanan)", "R", 3),
      val("pv-kl-4", "Standard / SNI", "STD", 4),
      val("pv-kl-5", "JIS", "JIS", 5),
    ]),
    attr("attr-pip-aplikasi", "Pipa & Sanitasi", "Aplikasi", 5, [
      val("pv-ap-1", "Instalasi Air Bersih", "AB", 1),
      val("pv-ap-2", "Saluran / Air Limbah", "AL", 2),
      val("pv-ap-3", "Tekanan / Pompa", "TK", 3),
      val("pv-ap-4", "Sanitari / Kamar Mandi", "SAN", 4),
    ]),
    attr("attr-pip-merk", "Pipa & Sanitasi", "Merk", 6, [
      val("pv-mk-1", "Rucika", "RUC", 1),
      val("pv-mk-2", "Wavin", "WAV", 2),
      val("pv-mk-3", "Roto", "ROT", 3),
      val("pv-mk-4", "Onda", "OND", 4),
      val("pv-mk-5", "Toto", "TOT", 5),
      val("pv-mk-6", "American Standard", "AMS", 6),
    ]),

    attr("attr-krm-jenis", "Keramik & Lantai", "Jenis", 1, [
      val("kr-jn-1", "Keramik Lantai", "KLT", 1),
      val("kr-jn-2", "Keramik Dinding", "KDN", 2),
      val("kr-jn-3", "Granit / Granito", "GRT", 3),
      val("kr-jn-4", "Homogen", "HMG", 4),
      val("kr-jn-5", "Mosaic / Mozaik", "MOS", 5),
      val("kr-jn-6", "Step Nosing / Sudut", "STP", 6),
    ]),
    attr("attr-krm-ukuran", "Keramik & Lantai", "Ukuran", 2, [
      val("kr-uk-1", "20x20 cm", "2020", 1),
      val("kr-uk-2", "25x40 cm", "2540", 2),
      val("kr-uk-3", "30x30 cm", "3030", 3),
      val("kr-uk-4", "40x40 cm", "4040", 4),
      val("kr-uk-5", "60x60 cm", "6060", 5),
      val("kr-uk-6", "80x80 cm", "8080", 6),
      val("kr-uk-7", "30x60 cm", "3060", 7),
    ]),
    attr("attr-krm-finish", "Keramik & Lantai", "Finish", 3, [
      val("kr-fn-1", "Glazur / Kilat", "GLZ", 1),
      val("kr-fn-2", "Matt", "MAT", 2),
      val("kr-fn-3", "Polished", "POL", 3),
      val("kr-fn-4", "Rustic / Tekstur", "RST", 4),
      val("kr-fn-5", "Antislip", "ASL", 5),
    ]),
    attr("attr-krm-warna", "Keramik & Lantai", "Warna / Motif", 4, [
      val("kr-wr-1", "Putih", "WHT", 1),
      val("kr-wr-2", "Abu / Grey", "GRY", 2),
      val("kr-wr-3", "Coklat / Wood", "BRN", 3),
      val("kr-wr-4", "Marmer", "MRM", 4),
      val("kr-wr-5", "Polos / Solid", "PLS", 5),
    ]),
    attr("attr-krm-tebal", "Keramik & Lantai", "Tebal", 5, [
      val("kr-tb-1", "7 mm", "7MM", 1),
      val("kr-tb-2", "8 mm", "8MM", 2),
      val("kr-tb-3", "9 mm", "9MM", 3),
      val("kr-tb-4", "10 mm", "10MM", 4),
    ]),
    attr("attr-krm-merk", "Keramik & Lantai", "Merk", 6, [
      val("kr-mk-1", "Roman", "ROM", 1),
      val("kr-mk-2", "Mulia", "MUL", 2),
      val("kr-mk-3", "Asia Tile", "AST", 3),
      val("kr-mk-4", "Granito", "GNT", 4),
      val("kr-mk-5", "Platinum", "PLT", 5),
      val("kr-mk-6", "IKA / Ikea", "IKA", 6),
    ]),

    attr("attr-bsi-jenis", "Besi & Logam", "Jenis", 1, [
      val("bs-jn-1", "Besi Beton", "BTN", 1),
      val("bs-jn-2", "Besi Hollow", "HOL", 2),
      val("bs-jn-3", "Besi Siku", "SIK", 3),
      val("bs-jn-4", "UNP / H-Beam", "UNP", 4),
      val("bs-jn-5", "Kawat Beton / Bendrat", "KWT", 5),
      val("bs-jn-6", "Paku", "PAK", 6),
      val("bs-jn-7", "Wiremesh", "WMS", 7),
      val("bs-jn-8", "Plat Besi", "PLT", 8),
    ]),
    attr("attr-bsi-ukuran", "Besi & Logam", "Ukuran", 2, [
      val("bs-uk-1", "6 mm", "6", 1),
      val("bs-uk-2", "8 mm", "8", 2),
      val("bs-uk-3", "10 mm", "10", 3),
      val("bs-uk-4", "12 mm", "12", 4),
      val("bs-uk-5", "4x4 cm", "4X4", 5),
      val("bs-uk-6", "4x6 cm", "4X6", 6),
      val("bs-uk-7", "2x4 cm", "2X4", 7),
      val("bs-uk-8", "1 kg / per kg", "1KG", 8),
    ]),
    attr("attr-bsi-panjang", "Besi & Logam", "Panjang", 3, [
      val("bs-pj-1", "6 m", "6M", 1),
      val("bs-pj-2", "12 m", "12M", 2),
      val("bs-pj-3", "5.8 m", "58M", 3),
      val("bs-pj-4", "Per batang", "BTG", 4),
      val("bs-pj-5", "Per kg", "KG", 5),
    ]),
    attr("attr-bsi-spes", "Besi & Logam", "Spesifikasi", 4, [
      val("bs-sp-1", "Polos", "PLS", 1),
      val("bs-sp-2", "Ulir / Deformed", "ULR", 2),
      val("bs-sp-3", "Galvanis", "GLV", 3),
      val("bs-sp-4", "Hitam", "HTM", 4),
      val("bs-sp-5", "Wiremesh M8", "M8", 5),
    ]),
    attr("attr-bsi-aplikasi", "Besi & Logam", "Aplikasi", 5, [
      val("bs-ap-1", "Struktur / Cor", "STR", 1),
      val("bs-ap-2", "Rangka / Hollow", "RNG", 2),
      val("bs-ap-3", "Perkuat / Tulangan", "PRK", 3),
      val("bs-ap-4", "Finishing / Paku", "FNS", 4),
    ]),
    attr("attr-bsi-merk", "Besi & Logam", "Merk", 6, [
      val("bs-mk-1", "Krakatau Steel", "KRA", 1),
      val("bs-mk-2", "Master Steel", "MST", 2),
      val("bs-mk-3", "Gunung Garuda", "GGD", 3),
      val("bs-mk-4", "JIS / Import", "JIS", 4),
      val("bs-mk-5", "Lokal", "LOC", 5),
    ]),

    attr("attr-kyu-jenis", "Kayu & Triplek", "Jenis", 1, [
      val("ky-jn-1", "Triplek", "TPL", 1),
      val("ky-jn-2", "Multiplek", "MPL", 2),
      val("ky-jn-3", "Kayu Meranti", "MRT", 3),
      val("ky-jn-4", "Kayu Jati", "JTI", 4),
      val("ky-jn-5", "Reng / Kaso", "RNG", 5),
      val("ky-jn-6", "Papan / Board", "PPN", 6),
      val("ky-jn-7", "Lis / Moulding", "LIS", 7),
      val("ky-jn-8", "MDF / Particle Board", "MDF", 8),
    ]),
    attr("attr-kyu-ukuran", "Kayu & Triplek", "Ukuran", 2, [
      val("ky-uk-1", "3 mm", "3MM", 1),
      val("ky-uk-2", "9 mm", "9MM", 2),
      val("ky-uk-3", "12 mm", "12MM", 3),
      val("ky-uk-4", "15 mm", "15MM", 4),
      val("ky-uk-5", "18 mm", "18MM", 5),
      val("ky-uk-6", "4x6 cm", "4X6", 6),
      val("ky-uk-7", "5x7 cm", "5X7", 7),
    ]),
    attr("attr-kyu-grade", "Kayu & Triplek", "Grade", 3, [
      val("ky-gr-1", "Grade A", "A", 1),
      val("ky-gr-2", "Grade B", "B", 2),
      val("ky-gr-3", "BC", "BC", 3),
      val("ky-gr-4", "MR (Moisture Resistant)", "MR", 4),
      val("ky-gr-5", "WR / Marine", "WR", 5),
    ]),
    attr("attr-kyu-treatment", "Kayu & Triplek", "Treatment", 4, [
      val("ky-tr-1", "Natural", "NAT", 1),
      val("ky-tr-2", "Oven / Kiln Dry", "OVN", 2),
      val("ky-tr-3", "Pressure Treated", "PT", 3),
      val("ky-tr-4", "Standar", "STD", 4),
    ]),
    attr("attr-kyu-merk", "Kayu & Triplek", "Merk", 5, [
      val("ky-mk-1", "Jaya Wood", "JWD", 1),
      val("ky-mk-2", "Pertiwi", "PTW", 2),
      val("ky-mk-3", "Korindo", "KRD", 3),
      val("ky-mk-4", "Lokal", "LOC", 4),
    ]),

    attr("attr-atp-jenis", "Atap & Rangka", "Jenis", 1, [
      val("at-jn-1", "Genteng Beton", "GBT", 1),
      val("at-jn-2", "Genteng Keramik / Tanah Liat", "GKR", 2),
      val("at-jn-3", "Spandek / Metal Roof", "SPD", 3),
      val("at-jn-4", "Rangka Baja Ringan", "RBG", 4),
      val("at-jn-5", "Reng / Kaso Atap", "RNG", 5),
      val("at-jn-6", "Nok / Wuwungan", "NOK", 6),
      val("at-jn-7", "Talang / Flashing", "TLG", 7),
    ]),
    attr("attr-atp-ukuran", "Atap & Rangka", "Ukuran", 2, [
      val("at-uk-1", "Standard", "STD", 1),
      val("at-uk-2", "Large / Super", "LRG", 2),
      val("at-uk-3", "Multi Roster", "MRS", 3),
      val("at-uk-4", "0.35 mm", "035", 4),
      val("at-uk-5", "0.40 mm", "040", 5),
      val("at-uk-6", "6 m", "6M", 6),
    ]),
    attr("attr-atp-material", "Atap & Rangka", "Material", 3, [
      val("at-mt-1", "Beton", "BTN", 1),
      val("at-mt-2", "Tanah Liat / Keramik", "TLK", 2),
      val("at-mt-3", "Galvalum", "GLV", 3),
      val("at-mt-4", "Zincalume", "ZNC", 4),
      val("at-mt-5", "Baja Ringan", "BJR", 5),
    ]),
    attr("attr-atp-warna", "Atap & Rangka", "Warna", 4, [
      val("at-wr-1", "Merah", "RED", 1),
      val("at-wr-2", "Hitam", "BLK", 2),
      val("at-wr-3", "Abu / Silver", "GRY", 3),
      val("at-wr-4", "Coklat / Natural", "BRN", 4),
      val("at-wr-5", "Putih", "WHT", 5),
    ]),
    attr("attr-atp-merk", "Atap & Rangka", "Merk", 5, [
      val("at-mk-1", "Mulia / Multi", "MUL", 1),
      val("at-mk-2", "Bluescope / Lysaght", "BLS", 2),
      val("at-mk-3", "Cisangkan", "CSK", 3),
      val("at-mk-4", "Lokal", "LOC", 4),
    ]),

    attr("attr-lst-jenis", "Listrik", "Jenis", 1, [
      val("ls-jn-1", "Kabel", "KBL", 1),
      val("ls-jn-2", "Stop Kontak", "STP", 2),
      val("ls-jn-3", "Saklar", "SKL", 3),
      val("ls-jn-4", "MCB / Breaker", "MCB", 4),
      val("ls-jn-5", "Lampu / Fitting", "LMP", 5),
      val("ls-jn-6", "Pipa Conduit", "CND", 6),
      val("ls-jn-7", "Box / Junction", "BOX", 7),
      val("ls-jn-8", "Klem / Aksesoris", "AKS", 8),
    ]),
    attr("attr-lst-kapasitas", "Listrik", "Kapasitas", 2, [
      val("ls-kp-1", "1.5 mm²", "15", 1),
      val("ls-kp-2", "2.5 mm²", "25", 2),
      val("ls-kp-3", "4 mm²", "4", 3),
      val("ls-kp-4", "6A", "6A", 4),
      val("ls-kp-5", "10A", "10A", 5),
      val("ls-kp-6", "16A", "16A", 6),
      val("ls-kp-7", "20A", "20A", 7),
      val("ls-kp-8", "E27 / Standard", "E27", 8),
    ]),
    attr("attr-lst-spes", "Listrik", "Spesifikasi", 3, [
      val("ls-sp-1", "NYM", "NYM", 1),
      val("ls-sp-2", "NYY", "NYY", 2),
      val("ls-sp-3", "NYA", "NYA", 3),
      val("ls-sp-4", "Indoor", "IND", 4),
      val("ls-sp-5", "Outdoor / Waterproof", "OUT", 5),
      val("ls-sp-6", "1 Phase", "1P", 6),
      val("ls-sp-7", "3 Phase", "3P", 7),
    ]),
    attr("attr-lst-warna", "Listrik", "Warna Kabel", 4, [
      val("ls-wr-1", "Merah", "RED", 1),
      val("ls-wr-2", "Hitam", "BLK", 2),
      val("ls-wr-3", "Biru / Netral", "BLU", 3),
      val("ls-wr-4", "Kuning / Ground", "YLW", 4),
      val("ls-wr-5", "Campuran / Roll", "MIX", 5),
    ]),
    attr("attr-lst-merk", "Listrik", "Merk", 5, [
      val("ls-mk-1", "Panasonic", "PNC", 1),
      val("ls-mk-2", "Schneider", "SCH", 2),
      val("ls-mk-3", "Utama / Maspion", "UTM", 3),
      val("ls-mk-4", "Broco", "BRC", 4),
      val("ls-mk-5", "Philips / Osram", "PHL", 5),
      val("ls-mk-6", "Omron / Hager", "OMR", 6),
    ]),

    attr("attr-ps-jenis", "Pasir & Material Curah", "Jenis", 1, [
      val("ps-jn-1", "Pasir Lumajang", "PLM", 1),
      val("ps-jn-2", "Pasir Putih", "PPT", 2),
      val("ps-jn-3", "Pasir Beton / Cor", "PBC", 3),
      val("ps-jn-4", "Batu Split", "SPL", 4),
      val("ps-jn-5", "Kerikil", "KRK", 5),
      val("ps-jn-6", "Tanah Urug", "TUR", 6),
      val("ps-jn-7", "Base Course / Batu Base", "BSC", 7),
    ]),
    attr("attr-ps-satuan", "Pasir & Material Curah", "Satuan Jual", 2, [
      val("ps-st-1", "per m³", "M3", 1),
      val("ps-st-2", "per Pikap", "PKP", 2),
      val("ps-st-3", "per Truk", "TRK", 3),
      val("ps-st-4", "per Rit", "RIT", 4),
      val("ps-st-5", "per Karung", "KRG", 5),
    ]),
    attr("attr-ps-sumber", "Pasir & Material Curah", "Sumber", 3, [
      val("ps-sm-1", "Lumajang", "LMJ", 1),
      val("ps-sm-2", "Bogor", "BGR", 2),
      val("ps-sm-3", "Karawang", "KRW", 3),
      val("ps-sm-4", "Lokal", "LOC", 4),
    ]),
    attr("attr-ps-gradasi", "Pasir & Material Curah", "Gradasi", 4, [
      val("ps-gr-1", "Halus", "HLS", 1),
      val("ps-gr-2", "Sedang", "SDG", 2),
      val("ps-gr-3", "Kasar", "KSR", 3),
      val("ps-gr-4", "Split 1-2 cm", "S12", 4),
      val("ps-gr-5", "Split 2-3 cm", "S23", 5),
    ]),

    // --- Aluminium (toko spesialis aluminium) ---
    attr("attr-alu-jenis", "Aluminium", "Jenis", 1, [
      val("alu-jn-1", "Profil Aluminium", "PRF", 1),
      val("alu-jn-2", "Plat Aluminium", "PLT", 2),
      val("alu-jn-3", "Hollow Aluminium", "HOL", 3),
      val("alu-jn-4", "Pipa Aluminium", "PIP", 4),
      val("alu-jn-5", "Aksesoris Aluminium", "AKS", 5),
      val("alu-jn-6", "Kawat Las Aluminium", "KWL", 6),
    ]),
    attr("attr-alu-ukuran", "Aluminium", "Ukuran", 2, [
      val("alu-uk-1", "1 inch", "1IN", 1),
      val("alu-uk-2", "2 inch", "2IN", 2),
      val("alu-uk-3", "3 inch", "3IN", 3),
      val("alu-uk-4", "4 inch", "4IN", 4),
      val("alu-uk-5", "40 x 40 mm", "4040", 5),
      val("alu-uk-6", "60 x 60 mm", "6060", 6),
    ]),
    attr("attr-alu-tebal", "Aluminium", "Tebal", 3, [
      val("alu-tb-1", "0.8 mm", "08", 1),
      val("alu-tb-2", "1.0 mm", "10", 2),
      val("alu-tb-3", "1.2 mm", "12", 3),
      val("alu-tb-4", "2.0 mm", "20", 4),
    ]),
    attr("attr-alu-finish", "Aluminium", "Finish", 4, [
      val("alu-fn-1", "Silver Anodize", "SLV", 1),
      val("alu-fn-2", "White Powder Coat", "WHT", 2),
      val("alu-fn-3", "Black Anodize", "BLK", 3),
      val("alu-fn-4", "Natural", "NAT", 4),
    ]),
    attr("attr-alu-merk", "Aluminium", "Merk", 5, [
      val("alu-mk-1", "Alexindo", "ALX", 1),
      val("alu-mk-2", "Star Aluminium", "STR", 2),
      val("alu-mk-3", "Aluminium Alloy", "ALY", 3),
      val("alu-mk-4", "Lokal", "LOC", 4),
    ]),

    // --- PVC (plafon & material PVC) ---
    attr("attr-pvc-jenis", "PVC", "Jenis", 1, [
      val("pvc-jn-1", "Plafon PVC", "PLF", 1),
      val("pvc-jn-2", "Papan PVC / Panel", "PNL", 2),
      val("pvc-jn-3", "Profil Plafon", "PRF", 3),
      val("pvc-jn-4", "Lis PVC", "LIS", 4),
      val("pvc-jn-5", "Aksesoris Plafon", "AKS", 5),
      val("pvc-jn-6", "Pipa PVC Plafon", "PIP", 6),
    ]),
    attr("attr-pvc-ukuran", "PVC", "Ukuran", 2, [
      val("pvc-uk-1", "20 cm", "20C", 1),
      val("pvc-uk-2", "25 cm", "25C", 2),
      val("pvc-uk-3", "30 cm", "30C", 3),
      val("pvc-uk-4", "60 x 60 cm", "6060", 4),
      val("pvc-uk-5", "10 cm", "10C", 5),
    ]),
    attr("attr-pvc-warna", "PVC", "Warna", 3, [
      val("pvc-wr-1", "Putih", "WHT", 1),
      val("pvc-wr-2", "Krem", "CRM", 2),
      val("pvc-wr-3", "Kayu / Woodgrain", "WOD", 3),
      val("pvc-wr-4", "Silver", "SLV", 4),
    ]),
    attr("attr-pvc-motif", "PVC", "Motif", 4, [
      val("pvc-mt-1", "Polos", "PLS", 1),
      val("pvc-mt-2", "Marmer", "MRM", 2),
      val("pvc-mt-3", "Kayu", "KYU", 3),
      val("pvc-mt-4", "Geometric", "GEO", 4),
    ]),
    attr("attr-pvc-merk", "PVC", "Merk", 5, [
      val("pvc-mk-1", "Shunda Plafon", "SHN", 1),
      val("pvc-mk-2", "Kencana", "KNC", 2),
      val("pvc-mk-3", "Royal", "RYL", 3),
      val("pvc-mk-4", "Amstrong", "ARM", 4),
    ]),

    // --- Interior & Aksesoris (handle, kunci, engsel, sheet, dll.) ---
    attr("attr-int-jenis", "Interior & Aksesoris", "Jenis", 1, [
      val("int-jn-1", "Handle Pintu", "HND", 1),
      val("int-jn-2", "Kunci", "KNC", 2),
      val("int-jn-3", "Engsel", "ENG", 3),
      val("int-jn-4", "Rel Laci / Sliding", "REL", 4),
      val("int-jn-5", "Sheet HPL / Panel", "SHT", 5),
      val("int-jn-6", "Aksesoris Furniture", "AKS", 6),
      val("int-jn-7", "Slot / Mortise", "SLT", 7),
      val("int-jn-8", "Grendel / Door Stop", "GRD", 8),
    ]),
    attr("attr-int-ukuran", "Interior & Aksesoris", "Ukuran", 2, [
      val("int-uk-1", "4 inch", "4IN", 1),
      val("int-uk-2", "6 inch", "6IN", 2),
      val("int-uk-3", "8 inch", "8IN", 3),
      val("int-uk-4", "100 cm", "100", 4),
      val("int-uk-5", "122 x 244 cm", "122", 5),
    ]),
    attr("attr-int-finish", "Interior & Aksesoris", "Finish", 3, [
      val("int-fn-1", "SS / Stainless", "SS", 1),
      val("int-fn-2", "Chrome", "CRM", 2),
      val("int-fn-3", "Black Matte", "BLK", 3),
      val("int-fn-4", "Gold / Emas", "GLD", 4),
      val("int-fn-5", "Antique", "ANT", 5),
    ]),
    attr("attr-int-material", "Interior & Aksesoris", "Material", 4, [
      val("int-mt-1", "Stainless Steel", "SS", 1),
      val("int-mt-2", "Zinc Alloy", "ZNC", 2),
      val("int-mt-3", "HPL", "HPL", 3),
      val("int-mt-4", "PVC Edge", "PVC", 4),
    ]),
    attr("attr-int-merk", "Interior & Aksesoris", "Merk", 5, [
      val("int-mk-1", "Solid", "SLD", 1),
      val("int-mk-2", "Hafele", "HFL", 2),
      val("int-mk-3", "Boyolali", "BYL", 3),
      val("int-mk-4", "Krisbow", "KRS", 4),
      val("int-mk-5", "Lokal", "LOC", 5),
    ]),
  ];
}

/** Ringkasan urutan attribute — untuk UI bantuan kasir. */
export const CATEGORY_ATTRIBUTE_HINTS: Record<string, string> = {
  "Semen & Beton": "Jenis → kemasan → tipe → aplikasi → merk",
  "Bata & Blok": "Jenis → ukuran → kualitas → merk",
  "Cat & Finishing": "Jenis → kemasan → finishing → warna → merk",
  "Pipa & Sanitasi": "Jenis → bahan → ukuran → kelas → aplikasi → merk",
  "Keramik & Lantai": "Jenis → ukuran → finish → motif → tebal → merk",
  "Besi & Logam": "Jenis → ukuran → panjang → spesifikasi → aplikasi → merk",
  "Kayu & Triplek": "Jenis → ukuran → grade → treatment → merk",
  "Atap & Rangka": "Jenis → ukuran → material → warna → merk",
  Listrik: "Jenis → kapasitas → spesifikasi → warna kabel → merk",
  "Pasir & Material Curah": "Jenis → satuan jual → sumber → gradasi (nama: Jenis / Satuan)",
  Aluminium: "Jenis → ukuran → tebal → finish → merk",
  PVC: "Jenis → ukuran → warna → motif → merk",
  "Interior & Aksesoris": "Jenis → ukuran → finish → material → merk",
};
